apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress-ms
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: ms1-helm.dev
    http:
      paths:
      - path: /api/ms1
        pathType: Prefix
        backend:
          service:
            name: micro-service-1-srv
            port: 
              number: 4000
      - path: /api/ms2
        pathType: Prefix
        backend:
          service:
            name: micro-service-2-srv
            port: 
              number: 4000