apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadataName }}
  labels:
    {{- include "micro-service-2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "micro-service-2.selectorLabels" . | nindent 4 }}
